"""Freeze the CPython 3.11 / Unicode 14 behaviour used by the default replace functions.

The application reads only the generated header; it never runs Python for
the ten default \\F<> functions.
"""

import html
import html.entities
import re
import sys
import unicodedata
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "src/Misc/ReplaceFunctionsData.h"


def codepoints():
    for value in range(0x110000):
        if not 0xD800 <= value <= 0xDFFF:
            yield value


def u32(text):
    return 'U"' + "".join("\\U%08X" % ord(c) for c in text) + '"'


def ranges(values):
    result = []
    for value in values:
        if result and result[-1][1] + 1 == value:
            result[-1][1] = value
        else:
            result.append([value, value])
    return result


def final_sigma(text):
    return text.lower().endswith("\u03c2")


def main():
    if sys.version_info[:2] != (3, 11) or unicodedata.unidata_version != "14.0.0":
        raise SystemExit("regenerate with CPython 3.11 / Unicode 14.0.0")
    upper, lower, sets = [], [], {name: [] for name in (
        "lower", "upper", "cased", "ignorable", "space", "word", "digit")}
    for value in codepoints():
        char = chr(value)
        if char.upper() != char:
            upper.append((value, char.upper()))
        if char.lower() != char:
            lower.append((value, char.lower()))
        if char.islower():
            sets["lower"].append(value)
        if char.isupper():
            sets["upper"].append(value)
        # Final_Sigma only consults case-ignorable characters by skipping them.
        before = final_sigma("A" + char + "\u03a3")
        alone = final_sigma(char + "\u03a3")
        if before and not alone:
            sets["ignorable"].append(value)
        elif alone:
            sets["cased"].append(value)
        if re.match(r"\s", char):
            sets["space"].append(value)
        if re.match(r"\w", char):
            sets["word"].append(value)
        if re.match(r"\d", char):
            sets["digit"].append(value)

    folds = {}
    for letter in "abcdefghijklmnopqrstuvwxyz":
        pattern = re.compile(letter, re.I)
        folds[letter] = [value for value in codepoints() if pattern.fullmatch(chr(value))]
    union = sorted({value for values in folds.values() for value in values})
    if union != [value for value in codepoints() if re.fullmatch("[a-z]", chr(value), re.I)]:
        raise SystemExit("(?i)[a-z] is not the union of (?i) letters")
    dol = sorted(set(folds["d"] + folds["o"] + folds["l"]))
    if dol != [value for value in codepoints() if re.fullmatch("[dol]", chr(value), re.I)]:
        raise SystemExit("(?i)[dol] is not the union of (?i) letters")

    entities = sorted(html.entities.html5.items())
    invalid_refs = sorted(html._invalid_charrefs.items())
    invalid_points = sorted(html._invalid_codepoints)

    lines = [
        "// Generated by tests/generate_replace_functions_data.py from CPython %s (Unicode %s)."
        % (sys.version.split()[0], unicodedata.unidata_version),
        "// Do not edit by hand. The default replace functions must keep this legacy behaviour.",
        "#pragma once",
        "",
        "#include <cstdint>",
        "",
        "namespace ReplaceFunctionsData {",
        "",
        "struct Mapping { char32_t codepoint; const char32_t *text; };",
        "struct Range { char32_t first; char32_t last; };",
        "struct Entity { const char32_t *name; const char32_t *text; };",
        "struct CharRef { std::uint32_t number; char32_t codepoint; };",
        "",
    ]
    for name, table in (("UPPER", upper), ("LOWER", lower)):
        lines.append("inline constexpr Mapping %s[] = {" % name)
        lines += ["    {0x%X, %s}," % (value, u32(text)) for value, text in table]
        lines += ["};", ""]
    for name, values in sets.items():
        lines.append("inline constexpr Range %s[] = {" % (name.upper() + ("_SET" if name in ("lower", "upper") else "")))
        lines += ["    {0x%X, 0x%X}," % (first, last) for first, last in ranges(values)]
        lines += ["};", ""]
    lines.append("// Code points matching each ASCII letter under Python re.IGNORECASE.")
    for letter, values in folds.items():
        lines.append("inline constexpr char32_t FOLD_%s[] = {%s};"
                     % (letter.upper(), ", ".join("0x%X" % value for value in values)))
    lines.append("")
    lines.append("inline constexpr Entity HTML5[] = {")
    lines += ["    {%s, %s}," % (u32(name), u32(text)) for name, text in entities]
    lines += ["};", ""]
    lines.append("inline constexpr CharRef INVALID_CHARREFS[] = {")
    lines += ["    {0x%X, 0x%X}," % (number, ord(text)) for number, text in invalid_refs]
    lines += ["};", ""]
    lines.append("inline constexpr Range INVALID_CODEPOINTS[] = {")
    lines += ["    {0x%X, 0x%X}," % (first, last) for first, last in ranges(invalid_points)]
    lines += ["};", "", "}", ""]
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print("wrote", OUTPUT)


if __name__ == "__main__":
    main()
