"""Freeze the bundled unidecode table used by legacy manifest id generation.

The table comes from tests/fixtures/unidecode. The application reads only the
generated header.
"""

import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "tests/fixtures"))
from unidecode import unidecode


OUTPUT = ROOT / "src/BookManipulation/ManifestIdUnidecode.h"


def main():
    rows = []
    for codepoint in range(0x10000):
        if 0xD800 <= codepoint <= 0xDFFF:
            continue
        character = chr(codepoint)
        replacement = unidecode(character)
        if replacement != character:
            escaped = replacement.encode("unicode_escape").decode("ascii").replace('"', '\\"')
            rows.append(f'    {{0x{codepoint:04x}, "{escaped}"}},')
    text = "\n".join([
        "// Generated by tests/generate_manifest_id_unidecode.py from tests/fixtures/unidecode.",
        "// Do not edit by hand. Manifest ids must keep this legacy transliteration.",
        "#pragma once",
        "",
        "#include <QString>",
        "",
        "#include <algorithm>",
        "",
        "namespace ManifestIdUnidecode {",
        "",
        "struct Entry { char16_t code; const char *text; };",
        "",
        "inline constexpr Entry kEntries[] = {",
        *rows,
        "};",
        "",
        "inline QString transliterate(const QString &text)",
        "{",
        "    QString result;",
        "    for (QChar character : text) {",
        "        const char16_t code = character.unicode();",
        "        const auto begin = std::begin(kEntries);",
        "        const auto end = std::end(kEntries);",
        "        const auto found = std::lower_bound(begin, end, code, [](const Entry &entry, char16_t value) {",
        "            return entry.code < value;",
        "        });",
        "        result += found != end && found->code == code ? QString::fromUtf8(found->text) : QString(character);",
        "    }",
        "    return result;",
        "}",
        "",
        "}",
        "",
    ])
    OUTPUT.write_text(text, encoding="utf-8")
    print(f"wrote {len(rows)} replacements to {OUTPUT}")


if __name__ == "__main__":
    main()
