"""Regenerate the C++ GB18030 tables from the legacy CPython codec.

The checked-in table was generated with CPython 3.11.12, the current embedded
runtime. Run with that version before changing the frozen mapping. This script
is development tooling; the application only uses the generated C++ header.
"""

from pathlib import Path


OUTPUT = Path(__file__).resolve().parents[1] / "src" / "Misc" / "TxtEncodingTables.h"


def four_bytes(pointer):
    first = 0x81 + pointer // (10 * 126 * 10)
    pointer %= 10 * 126 * 10
    digit = 0x30 + pointer // (126 * 10)
    pointer %= 126 * 10
    third = 0x81 + pointer // 10
    last = 0x30 + pointer % 10
    return bytes((first, digit, third, last))


def main():
    two_byte = []
    for first in range(0x81, 0xFF):
        for second in (*range(0x40, 0x7F), *range(0x80, 0xFF)):
            decoded = bytes((first, second)).decode("gb18030")
            assert len(decoded) == 1 and ord(decoded) <= 0xFFFF
            two_byte.append(ord(decoded))

    ranges = []
    start = end = first_scalar = last_scalar = None
    for pointer in range(126 * 10 * 126 * 10):
        try:
            decoded = four_bytes(pointer).decode("gb18030")
            assert len(decoded) == 1
            scalar = ord(decoded)
        except UnicodeDecodeError:
            scalar = None
        if scalar is not None and end is not None and pointer == end + 1 and scalar == last_scalar + 1:
            end = pointer
            last_scalar = scalar
            continue
        if end is not None:
            ranges.append((start, end, first_scalar))
        start = end = pointer if scalar is not None else None
        first_scalar = last_scalar = scalar
    if end is not None:
        ranges.append((start, end, first_scalar))

    lines = [
        "// Generated by tests/generate_gb18030_table.py from the legacy CPython GB18030 codec.",
        "// Do not edit by hand; these values freeze the old TXT import mapping.",
        "#pragma once",
        "",
        "#include <cstdint>",
        "",
        "namespace TxtEncodingTables {",
        "",
        "inline constexpr std::uint16_t kTwoByte[] = {",
    ]
    for offset in range(0, len(two_byte), 12):
        lines.append("    " + ", ".join(f"0x{value:04x}" for value in two_byte[offset:offset + 12]) + ",")
    lines.extend(("};", "", "struct FourByteRange { int first; int last; char32_t first_scalar; };", "inline constexpr FourByteRange kFourByteRanges[] = {"))
    for first, last, scalar in ranges:
        lines.append(f"    {{{first}, {last}, 0x{scalar:06x}}},")
    lines.extend(("};", "", "}", ""))
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUTPUT}: {len(two_byte)} two-byte entries, {len(ranges)} four-byte ranges")


if __name__ == "__main__":
    main()
